// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33EZBgoGWSrfVjO5nP6mp-6ew6fxeE4Y',
    appId: '1:353712232762:web:a7a6cdb3d130b3ae459803',
    messagingSenderId: '353712232762',
    projectId: 'polyhouseie',
    authDomain: 'polyhouseie.firebaseapp.com',
    storageBucket: 'polyhouseie.appspot.com',
    measurementId: 'G-Z0HV89P4RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9BYSsg51gkybXxaEZ1m5x4ZFxDxsC-s',
    appId: '1:353712232762:android:002c3c2eefcefc8c459803',
    messagingSenderId: '353712232762',
    projectId: 'polyhouseie',
    storageBucket: 'polyhouseie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Kt92NF8cUtPlSJIatoNUaZcbYMwRAK4',
    appId: '1:353712232762:ios:d3c215dcfb305f34459803',
    messagingSenderId: '353712232762',
    projectId: 'polyhouseie',
    storageBucket: 'polyhouseie.appspot.com',
    iosClientId: '353712232762-9k385nn2fd681hp5fp8pbn09uc3cfi29.apps.googleusercontent.com',
    iosBundleId: 'com.example.polyhouseie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Kt92NF8cUtPlSJIatoNUaZcbYMwRAK4',
    appId: '1:353712232762:ios:d3c215dcfb305f34459803',
    messagingSenderId: '353712232762',
    projectId: 'polyhouseie',
    storageBucket: 'polyhouseie.appspot.com',
    iosClientId: '353712232762-9k385nn2fd681hp5fp8pbn09uc3cfi29.apps.googleusercontent.com',
    iosBundleId: 'com.example.polyhouseie',
  );
}
